execute @s[scores={level=..254,levelup_count=..-1}] ~~~ scoreboard players set @s levelup_count 0
execute @s[scores={level=255}] ~~~ function level/over
execute @s[scores={level=254}] ~~~ function level/lv255
execute @s[scores={level=253}] ~~~ function level/lv254
execute @s[scores={level=252}] ~~~ function level/lv253
execute @s[scores={level=251}] ~~~ function level/lv252
execute @s[scores={level=250}] ~~~ function level/lv251
execute @s[scores={level=249}] ~~~ function level/lv250
execute @s[scores={level=248}] ~~~ function level/lv249
execute @s[scores={level=247}] ~~~ function level/lv248
execute @s[scores={level=246}] ~~~ function level/lv247
execute @s[scores={level=245}] ~~~ function level/lv246
execute @s[scores={level=244}] ~~~ function level/lv245
execute @s[scores={level=243}] ~~~ function level/lv244
execute @s[scores={level=242}] ~~~ function level/lv243
execute @s[scores={level=241}] ~~~ function level/lv242
execute @s[scores={level=240}] ~~~ function level/lv241
execute @s[scores={level=239}] ~~~ function level/lv240
execute @s[scores={level=238}] ~~~ function level/lv239
execute @s[scores={level=237}] ~~~ function level/lv238
execute @s[scores={level=236}] ~~~ function level/lv237
execute @s[scores={level=235}] ~~~ function level/lv236
execute @s[scores={level=234}] ~~~ function level/lv235
execute @s[scores={level=233}] ~~~ function level/lv234
execute @s[scores={level=232}] ~~~ function level/lv233
execute @s[scores={level=231}] ~~~ function level/lv232
execute @s[scores={level=230}] ~~~ function level/lv231
execute @s[scores={level=229}] ~~~ function level/lv230
execute @s[scores={level=228}] ~~~ function level/lv229
execute @s[scores={level=227}] ~~~ function level/lv228
execute @s[scores={level=226}] ~~~ function level/lv227
execute @s[scores={level=225}] ~~~ function level/lv226
execute @s[scores={level=224}] ~~~ function level/lv225
execute @s[scores={level=223}] ~~~ function level/lv224
execute @s[scores={level=222}] ~~~ function level/lv223
execute @s[scores={level=221}] ~~~ function level/lv222
execute @s[scores={level=220}] ~~~ function level/lv221
execute @s[scores={level=219}] ~~~ function level/lv220
execute @s[scores={level=218}] ~~~ function level/lv219
execute @s[scores={level=217}] ~~~ function level/lv218
execute @s[scores={level=216}] ~~~ function level/lv217
execute @s[scores={level=215}] ~~~ function level/lv216
execute @s[scores={level=214}] ~~~ function level/lv215
execute @s[scores={level=213}] ~~~ function level/lv214
execute @s[scores={level=212}] ~~~ function level/lv213
execute @s[scores={level=211}] ~~~ function level/lv212
execute @s[scores={level=210}] ~~~ function level/lv211
execute @s[scores={level=209}] ~~~ function level/lv210
execute @s[scores={level=208}] ~~~ function level/lv209
execute @s[scores={level=207}] ~~~ function level/lv208
execute @s[scores={level=206}] ~~~ function level/lv207
execute @s[scores={level=205}] ~~~ function level/lv206
execute @s[scores={level=204}] ~~~ function level/lv205
execute @s[scores={level=203}] ~~~ function level/lv204
execute @s[scores={level=202}] ~~~ function level/lv203
execute @s[scores={level=201}] ~~~ function level/lv202
execute @s[scores={level=200}] ~~~ function level/lv201
execute @s[scores={level=199}] ~~~ function level/lv200
execute @s[scores={level=198}] ~~~ function level/lv199
execute @s[scores={level=197}] ~~~ function level/lv198
execute @s[scores={level=196}] ~~~ function level/lv197
execute @s[scores={level=195}] ~~~ function level/lv196
execute @s[scores={level=194}] ~~~ function level/lv195
execute @s[scores={level=193}] ~~~ function level/lv194
execute @s[scores={level=192}] ~~~ function level/lv193
execute @s[scores={level=191}] ~~~ function level/lv192
execute @s[scores={level=190}] ~~~ function level/lv191
execute @s[scores={level=189}] ~~~ function level/lv190
execute @s[scores={level=188}] ~~~ function level/lv189
execute @s[scores={level=187}] ~~~ function level/lv188
execute @s[scores={level=186}] ~~~ function level/lv187
execute @s[scores={level=185}] ~~~ function level/lv186
execute @s[scores={level=184}] ~~~ function level/lv185
execute @s[scores={level=183}] ~~~ function level/lv184
execute @s[scores={level=182}] ~~~ function level/lv183
execute @s[scores={level=181}] ~~~ function level/lv182
execute @s[scores={level=180}] ~~~ function level/lv181
execute @s[scores={level=179}] ~~~ function level/lv180
execute @s[scores={level=178}] ~~~ function level/lv179
execute @s[scores={level=177}] ~~~ function level/lv178
execute @s[scores={level=176}] ~~~ function level/lv177
execute @s[scores={level=175}] ~~~ function level/lv176
execute @s[scores={level=174}] ~~~ function level/lv175
execute @s[scores={level=173}] ~~~ function level/lv174
execute @s[scores={level=172}] ~~~ function level/lv173
execute @s[scores={level=171}] ~~~ function level/lv172
execute @s[scores={level=170}] ~~~ function level/lv171
execute @s[scores={level=169}] ~~~ function level/lv170
execute @s[scores={level=168}] ~~~ function level/lv169
execute @s[scores={level=167}] ~~~ function level/lv168
execute @s[scores={level=166}] ~~~ function level/lv167
execute @s[scores={level=165}] ~~~ function level/lv166
execute @s[scores={level=164}] ~~~ function level/lv165
execute @s[scores={level=163}] ~~~ function level/lv164
execute @s[scores={level=162}] ~~~ function level/lv163
execute @s[scores={level=161}] ~~~ function level/lv162
execute @s[scores={level=160}] ~~~ function level/lv161
execute @s[scores={level=159}] ~~~ function level/lv160
execute @s[scores={level=158}] ~~~ function level/lv159
execute @s[scores={level=157}] ~~~ function level/lv158
execute @s[scores={level=156}] ~~~ function level/lv157
execute @s[scores={level=155}] ~~~ function level/lv156
execute @s[scores={level=154}] ~~~ function level/lv155
execute @s[scores={level=153}] ~~~ function level/lv154
execute @s[scores={level=152}] ~~~ function level/lv153
execute @s[scores={level=151}] ~~~ function level/lv152
execute @s[scores={level=150}] ~~~ function level/lv151
execute @s[scores={level=149}] ~~~ function level/lv150
execute @s[scores={level=148}] ~~~ function level/lv149
execute @s[scores={level=147}] ~~~ function level/lv148
execute @s[scores={level=146}] ~~~ function level/lv147
execute @s[scores={level=145}] ~~~ function level/lv146
execute @s[scores={level=144}] ~~~ function level/lv145
execute @s[scores={level=143}] ~~~ function level/lv144
execute @s[scores={level=142}] ~~~ function level/lv143
execute @s[scores={level=141}] ~~~ function level/lv142
execute @s[scores={level=140}] ~~~ function level/lv141
execute @s[scores={level=139}] ~~~ function level/lv140
execute @s[scores={level=138}] ~~~ function level/lv139
execute @s[scores={level=137}] ~~~ function level/lv138
execute @s[scores={level=136}] ~~~ function level/lv137
execute @s[scores={level=135}] ~~~ function level/lv136
execute @s[scores={level=134}] ~~~ function level/lv135
execute @s[scores={level=133}] ~~~ function level/lv134
execute @s[scores={level=132}] ~~~ function level/lv133
execute @s[scores={level=131}] ~~~ function level/lv132
execute @s[scores={level=130}] ~~~ function level/lv131
execute @s[scores={level=129}] ~~~ function level/lv130
execute @s[scores={level=128}] ~~~ function level/lv129
execute @s[scores={level=127}] ~~~ function level/lv128
execute @s[scores={level=126}] ~~~ function level/lv127
execute @s[scores={level=125}] ~~~ function level/lv126
execute @s[scores={level=124}] ~~~ function level/lv125
execute @s[scores={level=123}] ~~~ function level/lv124
execute @s[scores={level=122}] ~~~ function level/lv123
execute @s[scores={level=121}] ~~~ function level/lv122
execute @s[scores={level=120}] ~~~ function level/lv121
execute @s[scores={level=119}] ~~~ function level/lv120
execute @s[scores={level=118}] ~~~ function level/lv119
execute @s[scores={level=117}] ~~~ function level/lv118
execute @s[scores={level=116}] ~~~ function level/lv117
execute @s[scores={level=115}] ~~~ function level/lv116
execute @s[scores={level=114}] ~~~ function level/lv115
execute @s[scores={level=113}] ~~~ function level/lv114
execute @s[scores={level=112}] ~~~ function level/lv113
execute @s[scores={level=111}] ~~~ function level/lv112
execute @s[scores={level=110}] ~~~ function level/lv111
execute @s[scores={level=109}] ~~~ function level/lv110
execute @s[scores={level=108}] ~~~ function level/lv109
execute @s[scores={level=107}] ~~~ function level/lv108
execute @s[scores={level=106}] ~~~ function level/lv107
execute @s[scores={level=105}] ~~~ function level/lv106
execute @s[scores={level=104}] ~~~ function level/lv105
execute @s[scores={level=103}] ~~~ function level/lv104
execute @s[scores={level=102}] ~~~ function level/lv103
execute @s[scores={level=101}] ~~~ function level/lv102
execute @s[scores={level=100}] ~~~ function level/lv101
execute @s[scores={level=99}] ~~~ function level/lv100
execute @s[scores={level=98}] ~~~ function level/lv99
execute @s[scores={level=97}] ~~~ function level/lv98
execute @s[scores={level=96}] ~~~ function level/lv97
execute @s[scores={level=95}] ~~~ function level/lv96
execute @s[scores={level=94}] ~~~ function level/lv95
execute @s[scores={level=93}] ~~~ function level/lv94
execute @s[scores={level=92}] ~~~ function level/lv93
execute @s[scores={level=91}] ~~~ function level/lv92
execute @s[scores={level=90}] ~~~ function level/lv91
execute @s[scores={level=89}] ~~~ function level/lv90
execute @s[scores={level=88}] ~~~ function level/lv89
execute @s[scores={level=87}] ~~~ function level/lv88
execute @s[scores={level=86}] ~~~ function level/lv87
execute @s[scores={level=85}] ~~~ function level/lv86
execute @s[scores={level=84}] ~~~ function level/lv85
execute @s[scores={level=83}] ~~~ function level/lv84
execute @s[scores={level=82}] ~~~ function level/lv83
execute @s[scores={level=81}] ~~~ function level/lv82
execute @s[scores={level=80}] ~~~ function level/lv81
execute @s[scores={level=79}] ~~~ function level/lv80
execute @s[scores={level=78}] ~~~ function level/lv79
execute @s[scores={level=77}] ~~~ function level/lv78
execute @s[scores={level=76}] ~~~ function level/lv77
execute @s[scores={level=75}] ~~~ function level/lv76
execute @s[scores={level=74}] ~~~ function level/lv75
execute @s[scores={level=73}] ~~~ function level/lv74
execute @s[scores={level=72}] ~~~ function level/lv73
execute @s[scores={level=71}] ~~~ function level/lv72
execute @s[scores={level=70}] ~~~ function level/lv71
execute @s[scores={level=69}] ~~~ function level/lv70
execute @s[scores={level=68}] ~~~ function level/lv69
execute @s[scores={level=67}] ~~~ function level/lv68
execute @s[scores={level=66}] ~~~ function level/lv67
execute @s[scores={level=65}] ~~~ function level/lv66
execute @s[scores={level=64}] ~~~ function level/lv65
execute @s[scores={level=63}] ~~~ function level/lv64
execute @s[scores={level=62}] ~~~ function level/lv63
execute @s[scores={level=61}] ~~~ function level/lv62
execute @s[scores={level=60}] ~~~ function level/lv61
execute @s[scores={level=59}] ~~~ function level/lv60
execute @s[scores={level=58}] ~~~ function level/lv59
execute @s[scores={level=57}] ~~~ function level/lv58
execute @s[scores={level=56}] ~~~ function level/lv57
execute @s[scores={level=55}] ~~~ function level/lv56
execute @s[scores={level=54}] ~~~ function level/lv55
execute @s[scores={level=53}] ~~~ function level/lv54
execute @s[scores={level=52}] ~~~ function level/lv53
execute @s[scores={level=51}] ~~~ function level/lv52
execute @s[scores={level=50}] ~~~ function level/lv51
execute @s[scores={level=49}] ~~~ function level/lv50
execute @s[scores={level=48}] ~~~ function level/lv49
execute @s[scores={level=47}] ~~~ function level/lv48
execute @s[scores={level=46}] ~~~ function level/lv47
execute @s[scores={level=45}] ~~~ function level/lv46
execute @s[scores={level=44}] ~~~ function level/lv45
execute @s[scores={level=43}] ~~~ function level/lv44
execute @s[scores={level=42}] ~~~ function level/lv43
execute @s[scores={level=41}] ~~~ function level/lv42
execute @s[scores={level=40}] ~~~ function level/lv41
execute @s[scores={level=39}] ~~~ function level/lv40
execute @s[scores={level=38}] ~~~ function level/lv39
execute @s[scores={level=37}] ~~~ function level/lv38
execute @s[scores={level=36}] ~~~ function level/lv37
execute @s[scores={level=35}] ~~~ function level/lv36
execute @s[scores={level=34}] ~~~ function level/lv35
execute @s[scores={level=33}] ~~~ function level/lv34
execute @s[scores={level=32}] ~~~ function level/lv33
execute @s[scores={level=31}] ~~~ function level/lv32
execute @s[scores={level=30}] ~~~ function level/lv31
execute @s[scores={level=29}] ~~~ function level/lv30
execute @s[scores={level=28}] ~~~ function level/lv29
execute @s[scores={level=27}] ~~~ function level/lv28
execute @s[scores={level=26}] ~~~ function level/lv27
execute @s[scores={level=25}] ~~~ function level/lv26
execute @s[scores={level=24}] ~~~ function level/lv25
execute @s[scores={level=23}] ~~~ function level/lv24
execute @s[scores={level=22}] ~~~ function level/lv23
execute @s[scores={level=21}] ~~~ function level/lv22
execute @s[scores={level=20}] ~~~ function level/lv21
execute @s[scores={level=19}] ~~~ function level/lv20
execute @s[scores={level=18}] ~~~ function level/lv19
execute @s[scores={level=17}] ~~~ function level/lv18
execute @s[scores={level=16}] ~~~ function level/lv17
execute @s[scores={level=15}] ~~~ function level/lv16
execute @s[scores={level=14}] ~~~ function level/lv15
execute @s[scores={level=13}] ~~~ function level/lv14
execute @s[scores={level=12}] ~~~ function level/lv13
execute @s[scores={level=11}] ~~~ function level/lv12
execute @s[scores={level=10}] ~~~ function level/lv11
execute @s[scores={level=9}] ~~~ function level/lv10
execute @s[scores={level=8}] ~~~ function level/lv9
execute @s[scores={level=7}] ~~~ function level/lv8
execute @s[scores={level=6}] ~~~ function level/lv7
execute @s[scores={level=5}] ~~~ function level/lv6
execute @s[scores={level=4}] ~~~ function level/lv5
execute @s[scores={level=3}] ~~~ function level/lv4
execute @s[scores={level=2}] ~~~ function level/lv3
execute @s[scores={level=1}] ~~~ function level/lv2