execute @s ~-1~~-1 detect ~~~ seichi:s_clay 0 setblock ~~~ air 0 destroy
execute @s ~-1~~ detect ~~~ seichi:s_clay 0 setblock ~~~ air 0 destroy
execute @s ~-1~~1 detect ~~~ seichi:s_clay 0 setblock ~~~ air 0 destroy
execute @s ~~~-1 detect ~~~ seichi:s_clay 0 setblock ~~~ air 0 destroy
execute @s ~~~ detect ~~~ seichi:s_clay 0 setblock ~~~ air 0 destroy
execute @s ~~~1 detect ~~~ seichi:s_clay 0 setblock ~~~ air 0 destroy
execute @s ~1~~-1 detect ~~~ seichi:s_clay 0 setblock ~~~ air 0 destroy
execute @s ~1~~ detect ~~~ seichi:s_clay 0 setblock ~~~ air 0 destroy
execute @s ~1~~1 detect ~~~ seichi:s_clay 0 setblock ~~~ air 0 destroy